name: Run WELA Audit

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019, windows-2022, windows-2025, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run configure bat(ASD)
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          cd bat
          ./ASD.bat

      - name: Run configure bat(MS Client)
        if: ${{ matrix.os == 'windows-2025' }}
        run: |
          cd bat
          ./Microsoft_Client.bat

      - name: Run configure bat(MS Server)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd bat
          ./Microsoft_Server.bat

      - name: Checkout WELA repository
        uses: actions/checkout@v4
        with:
          repository: Yamato-Security/WELA
          path: WELA

      - name: Run WELA.ps1 audit-settings
        run: |
          cd WELA
          ./WELA.ps1 audit-settings

      - name: Run WELA.ps1 audit-filesize
        run: |
          cd WELA
          ./WELA.ps1 audit-filesize

      - name: Move WELA result files (Default)
        if: ${{ matrix.os == 'windows-2019' }}
        run: |
          cd WELA
          Copy-Item *.csv ../data/Windows_Default/ -Force

      - name: Move WELA result files (ASD)
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          cd WELA
          Copy-Item *.csv ../data/Australian_Signals_Directorate/ -Force

      - name: Move WELA result files (Microsoft_Server)
        if: ${{ matrix.os == 'windows-2025' }}
        run: |
          cd WELA
          Copy-Item *.csv ../data/Microsoft_Server/ -Force

      - name: Move WELA result files (Microsoft_Client)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd WELA
          Copy-Item *.csv ../data/Microsoft_Client/ -Force

      - name: Run configure bat(YamatoSecurity)
        if: ${{ matrix.os == 'windows-2019' }}
        run: |
          cd bat
          ./YamatoSecurity.bat

      - name: Run WELA.ps1 audit-settings
        if: ${{ matrix.os == 'windows-2019' }}
        run: |
          cd WELA
          ./WELA.ps1 audit-settings

      - name: Run WELA.ps1 audit-filesize
        if: ${{ matrix.os == 'windows-2019' }}
        run: |
          cd WELA
          ./WELA.ps1 audit-filesize

      - name: Move WELA result files (Default)
        if: ${{ matrix.os == 'windows-2019' }}
        run: |
          cd WELA
          Copy-Item *.csv ../data/YamatoSecurity/ -Force