name: Run WELA Audit

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout bat repository
        uses: actions/checkout@v4
        with:
          repository: Yamato-Security/EnableWindowsLogSettings
          path: EnableWindowsLogSettings

      - name: Run EnableWindowsLogSettings
        run: |
          cd EnableWindowsLogSettings
          ./YamatoSecurityConfigureWinEventLogs.bat

      - name: Checkout WELA repository
        uses: actions/checkout@v4
        with:
          repository: Yamato-Security/WELA
          path: WELA

      - name: Run WELA.ps1 audit-settings
        run: |
          cd WELA
          ./WELA.ps1 audit-settings

      - name: Run WELA.ps1 audit-filesize
        run: |
          cd WELA
          ./WELA.ps1 audit-filesize

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: WELA/*.csv
