name: Run WELA Audit

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019, windows-2022, windows-2025, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run configure bat(ASD)
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          ./ASD.bat

      - name: Run configure bat(MS Client)
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          ./Microsoft_Client.bat

      - name: Run configure bat(MS Server)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          ./Microsoft_Server.bat

      - name: Checkout WELA repository
        uses: actions/checkout@v4
        with:
          repository: Yamato-Security/WELA
          path: WELA

      - name: Run WELA.ps1 audit-settings
        run: |
          cd WELA
          ./WELA.ps1 audit-settings

      - name: Run WELA.ps1 audit-filesize
        run: |
          cd WELA
          ./WELA.ps1 audit-filesize

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: WELA/*.csv
